export interface IModuleDic {
  MONITORING_ROUTES: 'MONITORING_ROUTES',
  MONITORING_METERS: 'MONITORING_METERS',
  SUBCATEGORIES: 'SUBCATEGORIES',
  METER_DEVICES: 'METER_DEVICE',
  USERS_GROUPS: 'USERS_GROUPS',
  METER_MODELS: 'METER_MODELS',
  TYPE_STATUS: 'TYPE_STATUS',
  METER_MARKS: 'METER_MARKS',
  METER_UNITS: 'METER_UNITS',
  GPS_DEVICE: 'GPS_DEVICE',
  GPS_MODELS: 'GPS_MODELS',
  CATEGORIES: 'CATEGORIES',
  GPS_MARKS: 'GPS_MARKS',
  STATIONS: 'STATIONS',
  STATUS: 'STATUS',
  FLEETS: 'FLEETS',
  TRUCKS: 'TRUCKS',
  CITIES: 'CITIES',
  USERS: 'USERS'
}

export type TModules =
  'MONITORING_ROUTES' |
  'MONITORING_METERS' |
  'SUBCATEGORIES' |
  'METER_DEVICE' |
  'USERS_GROUPS' |
  'METER_MODELS' |
  'TYPE_STATUS' |
  'METER_MARKS' |
  'METER_UNITS' |
  'GPS_DEVICE' |
  'GPS_MODELS' |
  'CATEGORIES' |
  'GPS_MARKS' |
  'STATIONS' |
  'STATUS' |
  'FLEETS' |
  'TRUCKS' |
  'CITIES' |
  'USERS'
